name: Linting

on:
  pull_request:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - .github

permissions:
  pull-requests: write
  checks: write

concurrency:
  group: 'code-quality'
  cancel-in-progress: false

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download oxlint
        run: ./script/download-oxlint.script.sh
      - name: lint
        run: ./oxlint --format=github ./src
