name: Linting

on:
  pull_request:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - .github

permissions:
  pull-requests: write
  checks: write

concurrency:
  group: 'code-quality'
  cancel-in-progress: false

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download oxlint
        run: ./script/download-oxlint.script.sh
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Lint changed files
        run: ./oxlint -- $(git diff --name-only --diff-filter=d ${{ github.base_ref || 'master' }} HEAD)